# Generated by Django 5.0.6 on 2024-07-03 11:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='amount',
            field=models.PositiveIntegerField(default=1, help_text='请输入大于等于1的正整数', validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
