# Generated by Django 5.0.6 on 2024-07-04 09:29

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0002_alter_document_amount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookshelf',
            options={'verbose_name': '书架', 'verbose_name_plural': '书架'},
        ),
        migrations.AlterModelOptions(
            name='document',
            options={'verbose_name': '文件', 'verbose_name_plural': '文件'},
        ),
        migrations.AlterModelOptions(
            name='filebook',
            options={'verbose_name': '档案盒', 'verbose_name_plural': '档案盒'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': '项目', 'verbose_name_plural': '项目'},
        ),
        migrations.RemoveField(
            model_name='document',
            name='amount',
        ),
        migrations.AddField(
            model_name='document',
            name='amount_now',
            field=models.PositiveIntegerField(default=1, verbose_name='库存'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='document',
            name='put_in_amount',
            field=models.PositiveIntegerField(default=1, help_text='请输入大于等于1的正整数', validators=[django.core.validators.MinValueValidator(1)], verbose_name='入库份数'),
        ),
        migrations.AddField(
            model_name='document',
            name='put_in_date',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='入库时间'),
        ),
        migrations.AddField(
            model_name='document',
            name='remark',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='备注'),
        ),
        migrations.AddField(
            model_name='filebook',
            name='put_in_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='入库时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='filebook',
            name='remark',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='备注'),
        ),
        migrations.AddField(
            model_name='project',
            name='intro',
            field=models.TextField(blank=True, null=True, verbose_name='项目简介'),
        ),
        migrations.AddField(
            model_name='project',
            name='year',
            field=models.CharField(default=2023, max_length=4, verbose_name='项目年份'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bookshelf',
            name='name',
            field=models.CharField(max_length=50, verbose_name='书架'),
        ),
        migrations.AlterField(
            model_name='document',
            name='filebook',
            field=models.ForeignKey(blank=True, max_length=200, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dms.filebook', verbose_name='档案盒'),
        ),
        migrations.AlterField(
            model_name='document',
            name='name',
            field=models.CharField(max_length=200, verbose_name='文件名'),
        ),
        migrations.AlterField(
            model_name='document',
            name='principal',
            field=models.CharField(max_length=100, verbose_name='交接人'),
        ),
        migrations.AlterField(
            model_name='filebook',
            name='bookshelf',
            field=models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, to='dms.bookshelf', verbose_name='书架'),
        ),
        migrations.AlterField(
            model_name='filebook',
            name='name',
            field=models.CharField(max_length=200, verbose_name='档案盒名字'),
        ),
        migrations.AlterField(
            model_name='filebook',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dms.project', verbose_name='项目名'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=100, verbose_name='项目名'),
        ),
    ]
