# Generated by Django 5.0.6 on 2024-07-04 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0003_alter_bookshelf_options_alter_document_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filebook',
            name='bookshelf',
        ),
        migrations.CreateModel(
            name='Cell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='格子')),
                ('bookshelf', models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, to='dms.bookshelf', verbose_name='书架')),
            ],
            options={
                'verbose_name': '格子',
                'verbose_name_plural': '格子',
            },
        ),
        migrations.AddField(
            model_name='filebook',
            name='cell',
            field=models.ForeignKey(default=0, max_length=50, on_delete=django.db.models.deletion.CASCADE, to='dms.cell', verbose_name='书架'),
            preserve_default=False,
        ),
    ]
