# Generated by Django 5.0.6 on 2024-07-04 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0004_remove_filebook_bookshelf_cell_filebook_cell'),
    ]

    operations = [
        migrations.AddField(
            model_name='filebook',
            name='bookshelf',
            field=models.ForeignKey(default=1, max_length=50, on_delete=django.db.models.deletion.CASCADE, to='dms.bookshelf', verbose_name='书架'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='filebook',
            name='cell',
            field=models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, to='dms.cell', verbose_name='格子'),
        ),
    ]
