# Generated by Django 5.0.6 on 2024-07-06 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0006_remove_filebook_bookshelf'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='short_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='项目简称'),
        ),
        migrations.AlterField(
            model_name='document',
            name='put_in_date',
            field=models.DateField(blank=True, null=True, verbose_name='入库时间'),
        ),
        migrations.AlterField(
            model_name='filebook',
            name='put_in_date',
            field=models.DateField(verbose_name='入库时间'),
        ),
    ]
