# Generated by Django 5.0.6 on 2024-07-06 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0007_project_short_name_alter_document_put_in_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='short_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='文件简称'),
        ),
        migrations.AlterField(
            model_name='project',
            name='short_name',
            field=models.CharField(max_length=50, verbose_name='项目简称'),
        ),
    ]
