# Generated by Django 5.0.6 on 2024-07-08 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0008_document_short_name_alter_project_short_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='document_file',
            field=models.FileField(blank=True, null=True, upload_to='documents/', verbose_name='文件'),
        ),
    ]
