# Generated by Django 5.0.6 on 2024-06-08 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BasicInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('territorial_bond_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=11)),
                ('treasury_bond_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=11)),
            ],
        ),
    ]
