# Generated by Django 5.0.6 on 2024-06-08 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_statement', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BasicInfo',
            new_name='Project',
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('capital_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=11)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financial_statement.project')),
            ],
        ),
        migrations.CreateModel(
            name='CapitalFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_time', models.DateField()),
                ('account', models.DecimalField(decimal_places=2, default=0.0, max_digits=11)),
                ('capital_type', models.CharField(choices=[('Territorial', 'Territorial'), ('Treasury', 'Treasury')], max_length=50)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financial_statement.project')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financial_statement.section')),
            ],
        ),
    ]
