# Generated by Django 5.0.6 on 2024-07-03 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_statement', '0004_projectinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='capitalflow',
            name='remark',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
