# Generated by Django 5.0.6 on 2024-09-09 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_statement', '0006_alter_capitalflow_capital_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='territorial_bond_total',
        ),
        migrations.RemoveField(
            model_name='project',
            name='treasury_bond_total',
        ),
        migrations.RemoveField(
            model_name='section',
            name='capital_total',
        ),
        migrations.AddField(
            model_name='project',
            name='abbr',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=11),
        ),
        migrations.AlterField(
            model_name='capitalflow',
            name='capital_type',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='ProjectInvestment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=11)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financial_statement.project')),
            ],
        ),
    ]
