# Generated by Django 5.0.6 on 2024-10-21 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_statement', '0009_rename_account_capitalflow_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='abbr',
            field=models.CharField(default='NULLL', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='section',
            name='company',
            field=models.CharField(default='COMPANY', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='section',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
